name: ci

on:
  push:
    branches:
      - "main"

jobs:
  openresty-1-27-1-2-1-focal:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PAT }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with: 
          platforms: arm
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/arm64
          driver: cloud
          endpoint: "taikzz/openresty"
          install: true
          cleanup: true
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          no-cache: true
          context: ./
          platforms: linux/arm/v7
          tags: "${{ vars.DOCKER_USER }}/openresty:1.27.1.2-1-focal"
          # For pull requests, export results to the build cache.
          # Otherwise, push to a registry.
          outputs: ${{ github.event_name == 'pull_request' && 'type=cacheonly' || 'type=registry' }}
